{% set name = "flake8-mutable" %}
{% set version = "1.2.0" %}
{% set sha256 = "ee9b77111b867d845177bbc289d87d541445ffcc6029a0c5c65865b42b18c6a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - flake8

test:
  commands:
    - "flake8 --version | grep flake-mutable:"

about:
  home: https://github.com/ebeweber/flake8-mutable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Flake8 plugin to check against using mutable values as default arguments.'
  dev_url: https://github.com/ebeweber/flake8-mutable

extra:
  recipe-maintainers:
    - dopplershift
