travis:
  secure:
    BINSTAR_TOKEN: doiV0M0lIKIqNk9JiWTLbMohfRwJAmcclSJMoQuh5FcxQWnufVQxPqIshu0d9sy+9SjxIJeLqfrMNFaqcz8lDutOraPnNBTYpy6v0xpQqN/BrBuEu/JlbhNw13JWGjfjFc/KpM6cKRi7nylcrPGO7U4EJPrCjf0VbmLph4uomQ+zKZz2S7UUjJKZbxze7DTVB4Od2dVPWLs884tO+lujlEe6bKkbNhXwDprUoTqTVB90Knd6NWxJ3VWnWuPEavK/cByEwBVq4PGbi17xvDwcWuRpNsMQKHsZQy03XC4nq0Jbs8jR8qoZB8Q7LU5NNX/im2i/MFS4j1/X2VcOaq07jh9TU+QP8zpd46BuMzL0O3b1UD6+11leOPG0RM9xm9SecpOUBA3oP4ZvrMPR66r9KbJIyF3SpMAMmjeQqLjLisM2aCssbTT9EdJxVwRdD1AMxOZc+MN6KnsWuFAT6z17pM0Oz+fLid4/vTZZqZlO/wcawvNIj6SV7dAqW120LNdHIQcrdLjFaWjKjdC7o2wHChjyJYVMpUGJERUlbpW3uVtpuaKekqM00EThUyc87TnNZwI80VjSSta0ZfOCw0iSLbSZaAJFKtY905wXBjvzwkC9P//IfBSqx0TkIGD5ctSauMBaXorJVqUWHKMbucN8vCm6c0AJ3SwbNwKR0C2rywI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
