travis:
  secure:
    BINSTAR_TOKEN: Lg5+gvYD8UlmANSd3oMoCdF7cD/dzSqe0M+Dr00vDQYGujDb4eZJnu2J0TvQ9q2y81+xufhIW6JqyFa2Pzoa9DhLQzChnviN3U1Oa84mLr2zohBoGT29qL0jPXN6rEhc3ZClZWifrjmLQ2EwkUQUmGW/E45s10B32oL6dpvtupn5lDrA/BIvaG7P9H9PNj/ovo23JN4Iwy2TfmB0A5As95EpHc0/mKcwTBk0ic+Or5Xw8QeKrq4Yk3vWaKezmwWagUfAVXknCeXnv/apPtz38P1Uyb3/zBzK65v3cRTOEH9R7v2UONGnIoOexMk6+Tesq3S/wmuLo66h2fNKVYmUmH7BbBfhoGZmeN9plmkQYYoyx99jccoxZKFLp1YiWWAjYyXEdp8f35Hbs6tBmbWFY8khp2JADkCuqLlRs/KnMeskshuKVgtShSQeZ5fdk8M+XG374PWZC9/8YER5Ht6i9V/tzHTQCGorcx7sZzNA7SjBHTpNv3lFF4vHPECq7ZwOVIanFZcLKFI0JT4A+VafmA4vMk6qX/udqOUV8IOjuGvd+NzMY6VxIgkg47wCpEPfulokhLv5FM15jQyZlJAJibPsLtQMs68ddiZO3w4HquGEUvW28GCYHq0Ffa3mFmV27rbavlksV9CqX7/M3tGaR5AQ0WLE1ov898RYBajKwnk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
