travis:
  secure:
    BINSTAR_TOKEN: Ei0u+q8CRBr48LWnYByBZN0bWKBvBWfWk11NcqqmhDfM8KDXPqERxaV/LkzbjwN0azU74RkxlKdMDxuA/nSAO7fmnNokEsxdXabyW2wZLptU7uuIh5Oz5dRR8wZcYkjYcLadjiNNC8duY388bNVu59ik8XtjJH6anaxGKqUDzHWMp4pgSz7WPPQNn66TZ9O0JKDqEAIYXk5CKtnCTcTX0O2XO5m/Pm7MWxCfSZf+KHGZLUUKL+fouTdu5eut1rLpzz25ZMi5Pv2CfGmNY+bwC+vab+hIYYfvVbQiXE0OBPvd2zfp4DBXLTgR+TldOt+3RJJkK8OcemQ2OynWKpEEj+cqQ0AwtjEvSXyM5Qur4l0EkRTCnyBV9VNQnqq9NcXS+s24XoXdBnafXeIzSstqjE+mHeYW7iV/nRVXrhXQzKX3yNlKIdMOTBlQDbg5i4o3PUZPfK+lyx+DCHoi1fuuL7NT+E9OoBGIAt1gOc07nLty7SbxPUkyuzFpcYdwgU99xdli200AicHyaOK9J94qAzalXn/x6D1F/N3757PBLPKi4hfeTpIXISQq1F08S2l6d8DTYuLZw4ruH+p5rnb8kWubmb+enylJiS4ZyqdnxlMLgTM34zPadXG+zeRaXzR4aUjF3mvmNBYRlSjjwOLp9d5M3ghMBBgeIdd5hyPlUp0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
